language: scala

os: linux
dist: trusty
sudo: required

before_install:
  - sudo apt-get install build-essential ocaml automake autoconf libtool
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - git clone https://github.com/ankurdave/linux-sgx -b c++11
  - cd linux-sgx
  - ./download_prebuilt.sh
  - make sdk_install_pkg
  - cd ..
  - echo yes | ./linux-sgx/linux/installer/bin/sgx_linux_x64_sdk_*.bin
  - source sgxsdk/environment
  - openssl ecparam -name prime256v1 -genkey -noout -out private_key.pem
  - export SPARKSGX_DATA_DIR=$PWD/data
  - export PRIVATE_KEY_PATH=$PWD/private_key.pem

script: sbt 'set ivyLoggingLevel := UpdateLogging.Quiet' test
