language: scala

os: linux
dist: trusty
sudo: required

before_install:
  - sudo apt-get install build-essential ocaml automake autoconf libtool
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - git clone https://github.com/intel/linux-sgx.git -b sgx_2.1.3
  - cd linux-sgx
  - ./download_prebuilt.sh
  - make --quiet sdk_install_pkg
  - echo yes | ./linux/installer/bin/sgx_linux_x64_sdk_*.bin
  - source sgxsdk/environment
  - cd ..
  - openssl ecparam -name prime256v1 -genkey -noout -out private_key.pem
  - export SPARKSGX_DATA_DIR=$PWD/data
  - export PRIVATE_KEY_PATH=$PWD/private_key.pem
  - ./data/fetch-test-data.sh

script: sbt -Dspark.ui.showConsoleProgress=false 'set ivyLoggingLevel := UpdateLogging.Quiet' test
