language: scala
scala: 2.12.10

os: linux
dist: bionic
jdk: openjdk8

before_install:

  - echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
  - wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-bionic-7.list
  - wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main" | sudo tee /etc/apt/sources.list.d/msprod.list
  - wget -qO - https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt update
  - sudo apt -y install clang-7 libssl-dev gdb libsgx-enclave-common libsgx-enclave-common-dev libprotobuf10 libsgx-dcap-ql libsgx-dcap-ql-dev
  - sudo apt-get -y install wget build-essential openjdk-8-jdk python libssl-dev
  - sudo apt-get -y install open-enclave=0.9.0
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.6/cmake-3.15.6-Linux-x86_64.sh
  - sudo bash cmake-3.15.6-Linux-x86_64.sh --skip-license --prefix=/usr/local
  - export PATH=/usr/local/bin:"$PATH"
  - cmake --version
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - java -version
  - openssl genrsa -out private_key.pem -3 3072
  - source opaqueenv
  - source /opt/openenclave/share/openenclave/openenclaverc
  - export MODE=SIMULATE
  - env
  - oesgx

script: sbt ++$TRAVIS_SCALA_VERSION -Dspark.ui.showConsoleProgress=false 'set ivyLoggingLevel := UpdateLogging.Quiet' test

# Cache SBT and Ivy artifacts
# From https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Clean up the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
