language: scala

os: linux
dist: trusty
sudo: required

before_install:
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - wget https://download.01.org/intel-sgx/linux-1.7/sgx_linux_x64_sdk_1.7.100.36470.bin -O sgx_sdk.bin
  - chmod +x sgx_sdk.bin
  - echo yes | ./sgx_sdk.bin
  - source sgxsdk/environment
  - openssl ecparam -name prime256v1 -genkey -noout -out private_key.pem
  - export SPARKSGX_DATA_DIR=$PWD/data
  - export LIBSGXENCLAVE_PATH=$PWD/libSGXEnclave.so
  - export LIBENCLAVESIGNED_PATH=$PWD/enclave.signed.so
  - export LIBSGX_SP_PATH=$PWD/libservice_provider.so
  - export PRIVATE_KEY_PATH=$PWD/private_key.pem
  - data/disease/synth-disease-data
